### ISSUE TITLE
向紫玥家长接送刷卡，妈妈收不到信息，爸爸能收到

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#115]

**Comment by underhill6** [comment]
1.查询之后发现妈妈(电话为15883626200)的用户在tb_weichat_bind中是标记删除的状态，在tb_user表中也没有该用户的数据;
2.重新添加tb_user表中的绑定数据;
3.用户已经可以正常进入宝贝中心，用户数据没有错误就可以正常收到信息了。
