### ISSUE TITLE
重庆某家长反映看到的照片是别家小朋友的

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#126]
具体15060939415 杨芷涵

**Comment by underhill6** [comment]
该家长绑定的小朋友名字是冉芷涵，studentId是20326，学校是酉阳县欣鑫幼儿园；
数据库中还存在杨芷涵这个小朋友，studentId是4387，学校是重庆巴南河畔名居幼儿园；
可能是绑定关系错误，还没有和家长确认绑定关系是否正确。

**Comment by underhill6** [comment]
后续跟进,问题:
酉阳县欣鑫幼儿园  学前班的梁照誉的信息总是发到大班冉芷涵妈妈手机上;
同事反馈的家长电话查询结果:
梁照誉  13638209632妈妈,openid为oVnnvv6OK2gjVtQI9JToanMqZvrg,微信昵称为"hhf",绑定了梁照誉小朋友的关系,但是为标记删除状态(userId 22141);
冉芷涵  15060939415妈妈,openid为oVnnvvxmTu8qil6BvBA3v_4aChvM,微信昵称为"点叮猫",绑定了两个冉芷涵小朋友的关系(userId 22151,22536)和一个梁照誉小朋友的关系(22150);
处理措施:
A.移除冉芷涵妈妈多余(userId 22151)和不正确的绑定关系(userId 22150);
B.恢复梁照誉妈妈的绑定关系为正常状态。
