### ISSUE TITLE
这个小朋友后台有绑定卡号，但是卡是无效卡,这个卡不是新绑定的，周五都能用的

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#128]
![wechatimg2760](https://user-images.githubusercontent.com/24886936/32153842-eac486ca-bd67-11e7-9700-6d4f30500f12.png)

**Comment by liaoqiangadapt** [comment]
咨询过廖全龙，小诺识别逻辑。怀疑学生的IC号被更改过，按逻辑，不可能不识别，需要联系家长确认信息

**Comment by liaoqiangadapt** [comment]
![2017-10-30_163312](https://user-images.githubusercontent.com/13218359/32161393-53414eae-bd90-11e7-9f61-42a51dff2873.png)

**Comment by liaoqiangadapt** [comment]
猜测应该是'23680', '1243877616'
