### ISSUE TITLE
姓名：张蚕 号码15117695823 绑定成功，点宝贝中心会进入绑定界面

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#130]

**Comment by underhill6** [comment]
查询结果:
A.该用户为老师;
B.绑定的微信openid为oVnnvv5ij0wRJDeuUH0_s386PWE0,微信昵称 "流年的记忆",可以正常使用;
C.在微信上搜索手机号码15117695823,微信昵称为"曾经的曾经",openid为"oVnnvv5WVYuTcJuEMdqf_pJMC9Rw",有绑定关系,但是没有绑定到tb_user表的数据;
处理措施:
A.添加openid为"oVnnvv5WVYuTcJuEMdqf_pJMC9Rw"的用户的绑定关系;
