### ISSUE TITLE
13881801533 侨女士 31号没有收到晨检信息

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#135]
13881801533 侨女士
31号没有收到晨检信息

**Comment by veraGe** [comment]
家长消息列表同一条晨检数据数据发送了很多次晨检通知。。。



-

**Comment by liaoqiangadapt** [comment]
已优化，出错概率肯定降低。待观察两天，没问题你们就关闭 issue 哈

**Comment by yang55** [comment]
31号没有收到晨检信息：原因,没有孩子的晨检记录，没有识别的学生也没有该孩子的记录
同时收到六条：php出现错误，现已修复。
