### ISSUE TITLE
相册交互优化。

### ISSUE THREAD

**Issue by teeela** [didanoDevelopers2017/didano-weiChat#142]
问题：目前一组照片只能单击显示一张照片，不能左右滑动显示一组中的其他照片，退出后才能选择其他照片；
优化：单击一张照片时，进入改组照片的浏览模式，可以左右滑动（具体交互方式可以参考老师风采中的个人相册。）

**Comment by veraGe** [comment]
修改成组件模式，解决以前的bug。能够正常的左右滑动
