### ISSUE TITLE
宝宝动态中，多个角色选择优化（例选择宝宝）。

### ISSUE THREAD

**Issue by teeela** [didanoDevelopers2017/didano-weiChat#144]
问题描述：一个家长绑定了多个孩子，进入“宝宝动态”时，会有一个默认的宝宝信息，在右侧会有“选择宝宝”的切换按钮；但是经常有家长忽略“选择宝宝”的选项，只能看一个宝宝的推送信息，经常为此苦恼。
解决方式：进入“宝宝动态”后，“选择宝宝”默认为展开模式，当用户有操作之后为收起状态。

**Comment by veraGe** [comment]
将设置显示的参数改成true。进入就是直接展开
