### ISSUE TITLE
唐孝龙的家长能够在监控时间段之外看到视频

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#147]
根据分析日志里面发现确实能看，估计是用户自己改的手机时间，因此，我们对于控制时间，需要采用系统时间，由系统提供时间才可以
![wechatimg3196](https://user-images.githubusercontent.com/24886936/32645650-4ee69cd8-c623-11e7-8dcc-0e6515340bd0.png)

**Comment by veraGe** [comment]
调用接口获取服务器是时间
