### ISSUE TITLE
短信异常回复语句不够人性话

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#150]
需要将回复语言植入常量，同时要写入日志表，先做日志表，将来再做成大数据分析

**Comment by stephenwang2017** [comment]
![wechatimg7](https://user-images.githubusercontent.com/24886936/32687186-06fe487e-c6f2-11e7-9caf-f7d05caaa004.jpeg)

**Comment by underhill6** [comment]
这个是微信客户端给出的提示语，出现的可能性如下:
1.用户点进去的是一个分享的测试号链接，但是用户并没有关注，点进去后就提示需要关注测试号的错误码，这样的场景我们已经复现出来，会出现这样的报错；
2.用户点击访问时参数传递出错，微信客户端报出这样的错误，用户退出重新点击访问后恢复正常;
