### ISSUE TITLE
本来应该家长收到晨检信息，她们园长也收到了

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#152]
![wechatimg3260](https://user-images.githubusercontent.com/24886936/32711287-48cc1870-c879-11e7-9bf6-9bcce68b1924.jpeg)
![wechatimg3261](https://user-images.githubusercontent.com/24886936/32711288-495d9372-c879-11e7-9aa9-c1cd22ae78fe.jpeg)
![wechatimg3263](https://user-images.githubusercontent.com/24886936/32711289-4a6f264a-c879-11e7-85c7-939b116e4c19.jpeg)

**Comment by underhill6** [comment]
A.园长电话:13372663888,openid为oVnnvvwmHkPKQ6IlDVwtiIkOCxnc;
B.小朋友家长电话:15025726297,openid为oVnnvvxpKyCu_AJ30yNl3xGYCRdQ;
C.问题原因:查看后发现家长用户的电话15025726297在10月27日既绑定了自己的微信号oVnnvvxpKyCu_AJ30yNl3xGYCRdQ,
也绑定了园长的微信号(即oVnnvvwmHkPKQ6IlDVwtiIkOCxnc),所以园长的微信绑定与该小朋友建立了绑定关系,收到了该小朋友的接送通知推送;
D.具体原因不确定,可能是园长用家长的电话绑定测试;
E.处理措施是:删除园长用家长电话建立的家长角色绑定关系;
