### ISSUE TITLE
后台数据与前端显示不一致。

### ISSUE THREAD

**Issue by zyywinner123** [didanoDevelopers2017/didano-weiChat#157]
小李账号以我的手机号码进入，后台数据库进行查看我的手机号码，user表里面并没有小李这个用户

**Comment by zyywinner123** [comment]
问题无法复现

**Comment by underhill6** [comment]
1.在宝贝中心中能够看见的用户,即已经绑定成功,在tb_user表中存在数据且没有被标记删除;
因此进入宝贝中心能看到的，在tb_user表中一定有这个用户的数据；
2.在家庭管理里只会查询用户与小朋友的关系数据，只要在tb_student_parent表和tb_school_parent表中有关系数据，即关系存在就会显示出来；如果用户没有做微信绑定，在tb_user表中没有数据也没关系。
