### ISSUE TITLE
 微信用户七彩玛瑙报 你好,已邦定.为什么打卡打不了呢

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#162]

**Comment by underhill6** [comment]
1.联系家长，问题为接送时刷家长IC卡报无效IC卡;
2.查询数据库，该用户的电话是13987198085，在tb_student_parent学生家长关系表中(主键id为45294)没有家长IC卡的绑定数据；
3.处理措施:让家长请求学校老师绑定IC卡,如果还有异常再联系我们。
