### ISSUE TITLE
某个家长多收到其它小朋友信息

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#166]
![wechatimg3399](https://user-images.githubusercontent.com/24886936/32880175-a94e30a0-cae7-11e7-8ce2-7ce379a93e85.jpeg)

**Comment by underhill6** [comment]
学校后台导入数据时错误，多个家长都是同一个电话，导致绑定时也绑定了另外的小朋友。处理措施为删除多余的绑定关系。
