### ISSUE TITLE
陈康文爸爸收到张芯语的信息

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#177]
![wechatimg302](https://user-images.githubusercontent.com/24886936/33107958-9c60e090-cf74-11e7-9806-6df24e4c3bb5.jpeg)

**Comment by underhill6** [comment]
A.陈康文小朋友student_id 21534,爸爸电话:13708486088;
	  张芯语小朋友student_id 21533,爸爸电话:15368001212;
	B.后台录入时张芯语小朋友爸爸的录成了陈康文小朋友爸爸的,陈爸爸绑定时就多绑定了张芯语小朋友,后面张芯语小朋友爸爸的电话已经被更正过来;
	C.处理措施:取消陈爸爸与张芯语的绑定;
