### ISSUE TITLE
叶定衢的妈妈收到杨燚罗的信息

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#178]
![wechatimg13](https://user-images.githubusercontent.com/24886936/33108014-e0587bbe-cf74-11e7-9ee2-a6ab30aca151.jpeg)

**Comment by underhill6** [comment]
A.叶定衢小朋友student_id 21664,妈妈电话: 13529002337;
	  杨燚罗小朋友student_id 21665,妈妈电话: 13577072969;
	B.后台录入时叶定衢小朋友妈妈的电话录成了杨燚罗小朋友妈妈的,叶妈妈绑定时就多绑定了杨燚罗小朋友,后面杨燚罗小朋友妈妈的电话已经被更正过来,并且未绑定;
	C.处理措施:取消叶定衢的妈妈与杨燚罗的绑定;
