### ISSUE TITLE
两个家长信息串了

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#180]
![wechatimg15](https://user-images.githubusercontent.com/24886936/33108210-0fc5fa06-cf76-11e7-9ac4-828eee347251.jpeg)

**Comment by underhill6** [comment]
A.孔衍杰小朋友student_id 22430,妈妈电话: 13888291860;
	  刘耘菲小朋友student_id 21566,妈妈电话: 13987626927;
	B.后台录入时刘耘菲小朋友妈妈的电话录成了孔衍杰小朋友妈妈的,孔妈妈绑定时就多绑定了刘耘菲小朋友,后面刘耘菲小朋友妈妈的电话已经被更正过来,并且未绑定;
	C.处理措施:取消孔衍杰的妈妈与刘耘菲的绑定;
