### ISSUE TITLE
广安翰林实验幼儿园芽芽中二班小姨绑定成功，用工程师角色查看没有绑定

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#183]

**Comment by underhill6** [comment]
A.杜金泽小朋友student_id 22411;小姨电话:15182682383;
	B.之前该用户绑定过,是绑定成功,不知道是什么原因,在后台删除掉了,但是在后台还有另一个关系数据,所以就会提示已经绑定;
	C.恢复已经删除的绑定关系;
