### ISSUE TITLE
广安翰林实验幼儿园，这两个小朋友的家长是同一个，可是宝贝中心就只有一个小朋友

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#184]
![wechatimg3593](https://user-images.githubusercontent.com/24886936/33108628-37252eda-cf78-11e7-816a-c2ec793d48bb.png)
![wechatimg3595](https://user-images.githubusercontent.com/24886936/33108631-3c5aee3a-cf78-11e7-9a4d-a17cf546a34e.png)
![wechatimg3596](https://user-images.githubusercontent.com/24886936/33108636-3ec42d80-cf78-11e7-9454-1eda4be91bb4.jpeg)

**Comment by underhill6** [comment]
A.吴金泽小朋友student_id 22290;妈妈电话:18784156518;
	  吴柯翰小朋友student_id 22371;妈妈电话:18784156518;
	B.查看系统记录,绑定时新增tb_weichat_bind表数据时,触发器在tb_user表中只增加了22290吴金泽小朋友,这个有异常,追查未发现异常;
	C.后面家长再绑定时会提示已经绑定;
	D.处理措施:给这个家长绑定另一个小朋友;
