### ISSUE TITLE
山东某学校园长曾庆红报四个小朋友卡报无效

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#19]
有四个小朋友卡报无效
![screenshot_20170907-095446_ b 751866e](https://user-images.githubusercontent.com/24886936/30143386-1d6f9026-93b8-11e7-97fa-7fad48b92df9.png)

**Comment by stephenwang2017** [comment]
需要老师将这几个小朋友家长的卡重新绑定一下，因为被删除调了

**Comment by yang55** [comment]
这个问题不是已经查询并且说明了原因了吗 ？
