### ISSUE TITLE
学校后台IC卡管理解绑失败

### ISSUE THREAD

**Issue by zyywinner123** [didanoDevelopers2017/didano-weiChat#192]
学校后台对学生IC卡a进行解绑操作后，提示解除绑定成功 然后再次搜索a仍然能够看到a的绑定关系，回到学生一览查看相关学生发现a的绑定关系依然存在。

**Comment by veraGe** [comment]
同一张卡的rfid在多个小朋友下面，导致了解绑的时候数据获取不到。数据正常时，是能正常的解绑的
