### ISSUE TITLE
学校后台导入功能需优化

### ISSUE THREAD

**Issue by zyywinner123** [didanoDevelopers2017/didano-weiChat#193]
1.上传表格数据内若有空行，空行后面数据全部不能导入，点击确定后会出现error页面。
2.姓名+出生日重复添加是可以的。（表内数据重复不可以，如果是已添加的则可以）
[测试结果.zip](https://github.com/didanoDevelopers2017/didano-weiChat/files/1498421/default.zip)

**Comment by liaoqiangadapt** [comment]
几经修改，剩下的1已经解决

**Comment by liaoqiangadapt** [comment]
班级 + 学生名称 + 学生性别 + 学生生日
唯一确定一个学生身份，问题2已解决
