### ISSUE TITLE
向紫玥家长无法进入宝贝中心

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#22]

**Comment by underhill6** [comment]
1).向紫玥student_id:10238(deleted),14947;
	2).查询14947绑定家长school_parent_id:29231(妈妈)电话(15883626200),29232(爸爸)电话(15008356963);
	3).妈妈在weichat_bind表中usage_type为21的有三条信息:weichat_id:13255,11379,13255;
	4).13255的openid为oVnnvv3enq8YIf6A1lxJnLstPqpo,地址是德阳;11379的openid为oVnnvv_ZabgI0TOWY0QkiOi2PG60,地址为德阳(采取的措施是将这条绑定信息deleted置为1,并将tb_user对应的信息deleted置为1);
	5).爸爸在weichat_bind表中usage_type为21的只有一条信息:weichat_id:16110,openid为oVnnvv3xhjFmLyPQhTw16XE-u7Nw;
