### ISSUE TITLE
重庆长寿晏家幼儿园 和 山西灵石常青幼儿园   全部都没有考勤记录。

### ISSUE THREAD

**Issue by underhill6** [didanoDevelopers2017/didano-weiChat#220]

**Comment by stephenwang2017** [comment]
重庆长寿晏家幼儿园 25
山西灵石常青幼儿园 90

**Comment by stephenwang2017** [comment]
重庆长寿晏家龙凤幼儿园
没有今日晨检数据
![2](https://user-images.githubusercontent.com/24886936/34345590-2749def2-ea2b-11e7-812d-101a2aa4dd1d.jpeg)

**Comment by orangeyts** [comment]
1 重庆长寿晏家龙凤幼儿园  重启 即可
2 经过抓包发现晨检数据是缺失，并且post 分隔线日期是昨天 2017-12-27
