### ISSUE TITLE
weichat_push表中，有一条数据始终处于待发送的状态

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#231]
SELECT COUNT( * ) , 
STATUS FROM tb_weichat_push
WHERE send_time LIKE  '2018-01-04%'
AND STATUS IN ( 7, 8, 9 ) 
GROUP BY STATUS 
LIMIT 0 , 30
7状态的数据，始终有一条

**Comment by orangeyts** [comment]
mns消息发送错误，已重试
