### ISSUE TITLE
微信端新增学生，提示该学生已经与家长绑定（但学校后台已经存在绑定信息）

### ISSUE THREAD

**Issue by zyywinner123** [didanoDevelopers2017/didano-weiChat#241]

**Comment by underhill6** [comment]
1.查看了这个小朋友与家长的绑定信息,在学校后台和微信端通讯录都能查询出来，但是在数据库中有deleted= 1的数据；
2.在通讯录中直接删除这个家长与小朋友的绑定关系，再重新绑定能够成功.
