### ISSUE TITLE
学校后台相册管理里面，图片显示特别慢

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#251]
需要根据实际情况添加裁剪后缀?x-oss-process=image/resize,m_lfit,h_240,w_320

http://image-didanuo.oss-cn-shenzhen.aliyuncs.com/detection/20171118/e3b4a5f98afe58f1e6dbb49530a18e5d.jpg?x-oss-process=image/resize,m_lfit,h_240,w_320

**Comment by YinChun2** [comment]
其他模块缩略图都按照实际情况添加了裁剪后缀
