### ISSUE TITLE
方嘉仪

### ISSUE THREAD

**Issue by orangeyts** [didanoDevelopers2017/didano-weiChat#261]
外婆手机二维码-刷卡报未绑定ic卡，重新开机也不行

**Comment by underhill6** [comment]
方嘉仪小朋友的外婆没有绑定ic卡，所以就报这样的错误。外婆的电话是18780293350。只需要给外婆添加上ic卡就可以了，在老师通讯录或者学校后台都可以。

**Comment by underhill6** [comment]
![image](https://user-images.githubusercontent.com/29136748/37575769-e6f3f174-2b63-11e8-8f9a-1165e0e71a4c.png)

**Comment by orangeyts** [comment]
school196_rel84797
admin后台任务补二维码没有加密，导致无法识别，已全量重新生成
