### ISSUE TITLE
公众号绑定

### ISSUE THREAD

**Issue by orangeyts** [didanoDevelopers2017/didano-weiChat#262]
红星红河婴幼儿园有个家长进入公众号绑定，结果弹出来是别的小朋友
电话号码18580349902
他家小朋友名字是   杨小小

**Comment by underhill6** [comment]
学校后台导入学生家长数据时错误，该家长的电话输入到了另一个小朋友的家长上面，导致学生家长关系关联错误。

**Comment by underhill6** [comment]
![image](https://user-images.githubusercontent.com/29136748/37588658-db767b16-2b9d-11e8-8def-a13749336930.png)
