### ISSUE TITLE
**阿里短信验证**

### ISSUE THREAD

**Issue by underhill6** [didanoDevelopers2017/didano-weiChat#265]
#短信模板 0-互以短信  1-阿里短信
oss.textModel=1

查询互以短信还剩多少条

**Comment by underhill6** [comment]
互亿短信剩余条数:13514

**Comment by underhill6** [comment]
![image](https://user-images.githubusercontent.com/29136748/37640657-97e69322-2c51-11e8-8a76-4da34bf267be.png)

**Comment by orangeyts** [comment]
张瑶瑶阿里短信已经测试过，现在互以短信还有1W多，用的差不多在换吧
