### ISSUE TITLE
遂宁市童博森幼儿园-220

### ISSUE THREAD

**Issue by orangeyts** [didanoDevelopers2017/didano-weiChat#276]
有四个家长都来找我说家长卡是无效卡，我登录一看，通讯录里面家长卡号没有了，我们都没有删除过

**Comment by orangeyts** [comment]
熊猫班的陈博文，刘辰-已加上
熊猫班杨靖琪家长

**Comment by yang55** [comment]
由于该问题在26号进行修复，26号之前在学校后台单独添加的小朋友家长卡是没有绑定成功的，没有卡号的家长重新绑定一次就ok了

**Comment by yang55** [comment]
26号修复了这个问题，之前在学校后台单个添加的家长卡不能绑定成功，重新绑定就ok了
