### ISSUE TITLE
天全幼儿园几个班小朋友看不了视频

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#32]
大一班的马天瑞，高蕊婷，王梦洁，李立言看不了视频

**Comment by yang55** [comment]
经过排查，当前该班级的这几个学生家长是可以看视频的，初步认为是之前的摄像头出现问题，只有这几个学生的家长向学校反馈这件事，然后摄像头又可以使用了，就可以看了，和学校交互的人交流了一下，可能是因为网络原因，也有可能是电源原因等等
