### ISSUE TITLE
周宇宸小朋友的家长看不到视频

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#33]
![wechatimg625](https://user-images.githubusercontent.com/24886936/30313913-91d0eb5a-97d1-11e7-90e0-c764274df683.jpeg)
而且休息室是空白页面

**Comment by yang55** [comment]
这个不是视频的问题，因为同一行的两个视频名称长度不一样，长度比较长的名称会换行，短的不会，就会空出一个视频图片的空白位置。

**Comment by yang55** [comment]
还有就是这个家长绑定了两个小朋友，都是周语晨，一个在大二班，一个在中三班，可能家长进入通讯录的时候默认的是大二班的小朋友，但是事实上他自己的孩子在中三班，大二班的是假数据，没有选择学生默认为大二班的话，导致他自己看不到中三班的班级视频，如果他自己知道可以选择小朋友，就可以手动的切换进入中三班的视频，我将那个小朋友遗留在大二班的数据已经清除，但是这样的数据我估计还有，想要查询到很麻烦，引起这样的原因我想到一个，可能老师在添加小朋友的时候添加错了，结果没有删除，然后又在其他班去添加一个，然后家长又不懂切换小朋友信息。
