### ISSUE TITLE
通讯录和学校后台数据显示不一致

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#34]
![wechatimg10](https://user-images.githubusercontent.com/24886936/30319637-fca2566a-97e2-11e7-81fc-9eaf9f325693.jpeg)
![wechatimg11](https://user-images.githubusercontent.com/24886936/30319641-fe1854cc-97e2-11e7-9d62-d25ab5633b7f.jpeg)

**Comment by stephenwang2017** [comment]
后台没有显示该小朋友的家长

**Comment by yang55** [comment]
问题结果已经查到，在通讯录中，家长的现实只进行查询tb_student_parent表中存在（不管在tb_school_parent中的家长是否存在）都会蒋电话号码和家长都会查询出来，而在php后台，在查询tb_school_parent时，只要里面的家长不存在，不管tb_student_parent中的家长存不存在，查询出来的结果都是没有家长信息的。和通讯录有一点区别。
