### ISSUE TITLE
php后台进行ic卡的绑定出现问题

### ISSUE THREAD

**Issue by yang55** [didanoDevelopers2017/didano-weiChat#38]
通讯录的绑定规则：只要在学生表或者家长表查询deleted=0的ic卡数据，如果没有查询到不管ic卡所属的学校是哪个，都可以进行绑定，然而，php后台只要ic卡不属于这个学校，但是没有人绑定过，都不可以进行绑定，所以在php后台绑定不属于该学校的ic卡都会出现问题（绑定状态为0的除外）

**Comment by stephenwang2017** [comment]
问题迁移到xiaonuo
