### ISSUE TITLE
微信号韩军告知无法看到晨检报告

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#39]
韩云松，13315253146或18531207011

**Comment by veraGe** [comment]
电话为18531207011

**Comment by veraGe** [comment]
韩云松openid = “oVnnvv94DH_z7kjaUek6JNASy920”，从用户微信号进入数据显示正常，报告未迁移之前跳转不正常。今天小朋友没有晨检，无法看到今天情况，明天在进行观察该用户。

**Comment by veraGe** [comment]
今天家长收到了晨检报告，报告数据正常，但是微信推送没有发送成功tb_weichat_push中的id = 783024,发送状态为0,3才是发送成功。

**Comment by veraGe** [comment]
9月18号家长收到了晨检报告，报告数据正常，照片正常，微信推送数据库显示发送成功，并未见异常现象。。
