### ISSUE TITLE
通过通讯录新加的小朋友在学校后台看不到

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#41]
![screenshot_2017-09-13-15-13-43-755_com tencent mm_ b a4b7905](https://user-images.githubusercontent.com/24886936/30364426-ca662910-9896-11e7-93b0-4d1d81406955.png)

**Comment by yang55** [comment]
问题已经查询出来，由于该学生有进行ic卡的绑定，但是在ic卡表中，所绑定的ic卡信息是删除的状态，php那边的sql应该是ic卡的信息被删除后，学生的信息都查询不出来引起的。
