### ISSUE TITLE
php学校后台sql出现问题

### ISSUE THREAD

**Issue by yang55** [didanoDevelopers2017/didano-weiChat#43]
php sql在查询学生信息的时候，学生绑定有ic，但是在ic卡表中的数据是删除的状态，就查询不出学生的信息，要改为，就算ic卡的数据存在删除的状态，查询学生信息时，学生信息会查出来，最多就是ic卡的信息查询不出来。

**Comment by stephenwang2017** [comment]
迁移到xiaonuo
