### ISSUE TITLE
大足金桂贝贝数据晨检图片异常

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#48]
[学校关注的需求20170914.xlsx](https://github.com/didanoDevelopers2017/didano-weiChat/files/1301834/20170914.xlsx)

**Comment by stephenwang2017** [comment]
![wechatimg166](https://user-images.githubusercontent.com/24886936/30413865-51970776-9953-11e7-8ada-5b65023d4b15.jpeg)

**Comment by veraGe** [comment]
陈思含妈妈手机号：15223172632， openid:oVnnvv4bLw0dKlHQYCNQ9PxOps5c，小朋友的student_id = 11895，该小朋友一共就只有三条数据，9月14号晨检发错了，发成其他小朋友的照片。情况1：小朋友带卡晨检，晨检时都是对的，出现以前的情况，照片串了；情况2：小朋友没有带晨检，小诺认错了。9月15号再继续跟踪一下。

**Comment by veraGe** [comment]
9月15号该小朋友并未有晨检信息。

**Comment by veraGe** [comment]
9月18号该小朋友并未有晨检信息

**Comment by veraGe** [comment]
9月19号该小朋友并未有晨检信息
