### ISSUE TITLE
心月星小二班熊予晟小朋友的家长收不到二维码;

### ISSUE THREAD

**Issue by underhill6** [didanoDevelopers2017/didano-weiChat#52]
1. 查询到的小朋友及家长信息如下,在tb_user表,tb_school_parent表,tb_student_parent表,tb_weichat表,tb_weichat_bind表等表中确认信息无异常;
小朋友学生id 10697,学校id 27,班级id 593;
绑定的家长id有19185,19186,20080,23873;
家长id 19185电话:13648385046 微信昵称"秋",openid:'oVnnvv1o2SbD8kJeSmc-fQQ9BQFo',weichatid:10954;
家长id 19186电话:13638377845 微信昵称"阿坤",openid:'oVnnvv5W_NhjrACKCwEAIhSJ5Njo',weichatid:11495;
家长id 20080电话:18523308331 微信昵称"卫兵",openid:'oVnnvvxtkU_sLWBZaJqepIuA6zJg',weichatid:11513;
家长id 23873电话:18979127902 微信昵称"成成",openid:'oVnnvv9S3A0bJtpq_QmJiD4blD_g',weichatid:12923;
2. tb_weichat_push表中查询无四个家长的消息推送记录;
3. tb_student_detection表中有小朋友9月15日早上8点30分左右的两条记录,id分别为:391106和391657;
具体原因待查询;

**Comment by stephenwang2017** [comment]
这个小朋友后面再也没有晨检了，不知道什么原因
