### ISSUE TITLE
错发信息

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#69]
黄一鸣妈妈每天早上收到其他小朋友的信息她妈妈电话是:13510966613.爸:18664688588.小朋友卡号:09571
蒲梓妍妈妈:18227560300.爸:15183502070小朋友卡号:09540

**Comment by underhill6** [comment]
IC卡绑定可能有错误，后期处理是工作人员更换了IC卡。
