### ISSUE TITLE
某家庭，家长卡和儿童卡功能有问题

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#74]
儿童卡显示绑定，但是刷不出来，家长卡显示没有绑定，但是把家长卡刷出来啦
![img_20171009_121055](https://user-images.githubusercontent.com/24886936/31326460-14b2d6ea-acfa-11e7-9570-a96eeb2138c9.jpg)
![img_20171009_121110](https://user-images.githubusercontent.com/24886936/31326461-15d8b18e-acfa-11e7-8b16-f069cffc4475.jpg)

**Comment by underhill6** [comment]
学生姓名:王渥丹 id: 18980, rfid:1244196208, ic_card_id:33610, 宝宝卡id:22242,信息确认没有问题;
家长id: 39910,rfid:1243215408,ic_card_id:36073,家长卡id:未知;

**Comment by underhill6** [comment]
后面再跟进，是否有问题。
