### ISSUE TITLE
二维码白板

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#76]
再次出现二维码白板现象
![sss](https://user-images.githubusercontent.com/24886936/31334841-927a92e8-ad22-11e7-815f-0dd7cb959ea7.jpg)

**Comment by liaoqiangadapt** [comment]
再次？ ？

**Comment by liaoqiangadapt** [comment]
解决的问题点：
1、学生家长表tb_student_parent.qrcode_url    tb_student_parent.qrcode_url_old 这两个字段有些家长为空，这个家长刚好是其中一例，现在已经废弃这两个字段（但不能删除哈，过度阶段，以后彻底废除），就是说这两个字段数据库为空或乱写影响很小。
2、还有一个问题，这个家长的二维码本身不存在，可能被人误删了。
