### ISSUE TITLE
马雅蓝小朋友，手机可以收到，儿童卡能用，家长卡用不了

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#77]
![27](https://user-images.githubusercontent.com/24886936/31335679-2dd78c48-ad26-11e7-8529-23705a2a39f1.jpg)
三幼，马雅蓝小朋友，手机可以收到，儿童卡能用，家长卡用不了

（卡的问题，三幼出现了几例

）

**Comment by liaoqiangadapt** [comment]
查无此人

**Comment by stephenwang2017** [comment]
统一处理了
