### ISSUE TITLE
手机验证码收不到

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#78]
某家长告之原来的手机号有错误，老师帮着修改了，但是在绑定的时候就是收不到验证码
13269104103 涿州培轩幼儿园

**Comment by veraGe** [comment]
运营商回执状态是发送成功，手机短信是发送到了该家长手机号码上面了。
10月9号，用户操作发送超过了5条，收不到短信。10月10号用户发送了两条成功了，并且查看用户已经和小朋友建立了绑定的关系。说明已经绑定成功。。

**Comment by stephenwang2017** [comment]
有个家长收不到手机验证码短信，经过检查，我们是通过短信平台发出去了，但是家长确实没有收到，后来经过短信平台的工程师检查，发现该家长手机号进入当地运营商的黑名单中，这边通过申请，将该家长从黑名单中移出，就可以了，这样的样例比较少，每次我们都需要通过短信平台的工程师去与运营商沟通，相当于转了三道程序才解决，总结 1）有的家长收不到短信验证码是因为他上了手机通讯运营商的黑名单，怎么上的，我们不清楚；2）如果遇到这种情况，除非家长强烈需求，我们才能找第三方工程师第四方工程师合作解决

**Comment by stephenwang2017** [comment]
退订短信，也会上黑名单，然后，一直就会收不到，上了黑名单，就一直是
