### ISSUE TITLE
三幼幼儿园二维码白板汇总

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#80]
![wechatimg1781](https://user-images.githubusercontent.com/24886936/31377040-65258c28-add9-11e7-8046-5bd87eb78298.jpeg)

**Comment by liaoqiangadapt** [comment]
我那部分解决，转交陈元

**Comment by liaoqiangadapt** [comment]
原来重新指派，那我关了
