### ISSUE TITLE
三幼无法绑定和手机号无法更改汇总

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#81]
![wechatimg1781](https://user-images.githubusercontent.com/24886936/31377115-97f4bba6-add9-11e7-89a6-5715807b8d37.jpeg)

**Comment by underhill6** [comment]
问题B.一个小朋友无法绑定
喻伍紫伊 sudent_id:19154,拥有两个家长关系,
家长1:parent_id 40265,电话号码13308092216,绑定成功,可以正常使用;
家长2:parent_id 40266,电话号码13628007228,tb_weichat_bind表中weichat_id值为0,不能查找到对应的微信用户,导致绑定失败;
处理措施:
a.删除电话号码13628007228在tb_weichat_bind中的数据,让用户重新绑定;

问题C.绑定的名字与手机号错误,且无法更改(或多个孩子名字);
陈泠然,sudent_id 19152 多绑定了(赵翢远小朋友的)家长,电话:18628086753,处理措施:删除多余的家长和家长关系;
李怡涵,sudent_id 19118 恢复两个家长的绑定关系,之前删除掉了,电话分别是13981919889和13880249391;
孙年孜,sudent_id 19153 查看后没有问题,绑定一个家长,妈妈电话:13518140271;
吴奕诺,sudent_id 19130 数据正常,绑定五个用户,比后台录入时多三个用户;
罗晨熙,sudent_id 19135 妈妈电话:13881982186,多绑定了一个小朋友朱锦融;
