### ISSUE TITLE
白雨川和白雨凡家长反映，两个孩子是双胞胎，今天家长收到两条晨检信息，但是都是同一个小朋友的

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#84]

**Comment by underhill6** [comment]
A.查询晨检表,昨天只有白雨凡小朋友有晨检数据,记录id为482559,今天在9点36小朋友各有一条晨检数据,晨检记录id分别是493100,493101;
B.信息推送表,昨天只有白雨凡小朋友有晨检推送,下午5过放学两个小朋友各有一条刷卡推送;
    		 今天两个小朋友都有晨检推送,中午11点23白雨川有刷卡的推送记录,下午5过放学白雨凡小朋友有一条刷卡的推送;
    		 所有推送的消息在系统里都记录为成功发送的。
