### ISSUE TITLE
部分金花幼儿园小朋友入园刷卡家长和老师收不到信息，有的显示的时间也不对

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#85]

**Comment by liaoqiangadapt** [comment]
![image](https://user-images.githubusercontent.com/13218359/31477100-ad4350d0-af3c-11e7-8aea-8f5bb4400d36.png)

**Comment by liaoqiangadapt** [comment]
1、时间不对是终端时间太不准确了，服务器莫法，找嵌入组吧
2、收不到信息，经排查，压根没提交晨检信息，比如黄晴小朋友 学生ID是18123

**Comment by liaoqiangadapt** [comment]
{
"id": "18122",
"class_id": "904",
"class_title": "学前一班",
"name": "杨晨悦",
"gender": "2",
"birthday": "2012-01-01",
"is_registered": "0",
"rfid_list": [
{
"ic_number": "1326",
"rfid": "1057886155"  家长的
},
{
"ic_number": "10025",
"rfid": "3713561764"  宝宝本人的
}
]
},




{
"id": "18123",
"class_id": "904",
"class_title": "学前一班",
"name": "黄晴",
"gender": "2",
"birthday": "2016-09-28",
"is_registered": "0",
-"rfid_list": [
-{
"ic_number": "1317",
"rfid": "1056688571"  家长的
},
-{
"ic_number": "10054",
"rfid": "3713251364"  宝宝本人的
}
]
},
