### ISSUE TITLE
三幼，有两个家长收到的小朋友信息，收到的是对方孩子的

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#86]
![wechatimg2025](https://user-images.githubusercontent.com/24886936/31474980-afbb0f80-af30-11e7-9173-4ce954971916.png)

**Comment by underhill6** [comment]
A.excel录入信息:
	中一班	赵翢远	男	2013-1-16,	06668	家长	18628084947,	36833	家长	18628086753;
	中一班	陈泠然	女	2013-2-4,	09506	家长	13551301882,	36852;																										
	B.数据库中绑定的家长:
	赵翢远 小朋友:studnet_id 19134 IC卡绑定卡号:06668 绑定了两个家长,40226的家长电话是18628084947,微信昵称'莱斯利',绑定了家长卡的卡号:36833和另一个40227的家长电话是18628086753,微信昵称'希希';
	陈泠然 小朋友:studnet_id 19152 IC卡绑定卡号:09506 绑定了一个家长,40263的家长电话是13551301882,绑定了家长卡的卡号:36852,微信昵称'小年宝贝儿';
	C.查询学校后台学生数据:
	学生名称	学生IC卡号	性别	生日	班级名称	家长信息											有效状态				创建时间 				
	赵翢远		06668		男	2013-01-16	中一班		妈妈		18628086753	主账号	x						是				2017-09-29 16:57:01
														爸爸	家长IC卡：36833	18628084947	主账号	x
	
	陈泠然		09506		女	2013-02-04	中一班		妈妈	家长IC卡：36852	13551301882	主账号	x			是				2017-09-29 16:57:01	
	D.确定电话号码与家长的绑定的微信帐号是一致的(在微信上搜索所有家长的电话,对应的微信都与数据库中的微信帐号一致);

**Comment by underhill6** [comment]
最终处理措施:
经学校同事联系家长,excel录入信息错误,正确数据如下:
		中一班	陈泠然	女	2013-02-04	09506	爸爸	18628084947	36852	妈妈	18628086753
		中一班	赵翢远	男	2013-01-16	06668	家长	13551301882	36833	家长	13518140271
	根据正确数据做更正;
