### ISSUE TITLE
泸州开心幼儿园彼得班邓辰宇家长的接送卡变成无效卡了

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#87]

**Comment by liaoqiangadapt** [comment]
问题多：
1、黄永反馈的卡号No.03033 根本没录入数据库，RFID压根不知
2、学生5003的家长没有RFID

tb_student_parent.student_id=5003
给爸爸、妈妈添加RFID即可

开心幼儿园  妈妈                 13882758998
开心幼儿园  邓辰宇爸比      15328333576

**Comment by liaoqiangadapt** [comment]
暂时没法解决，信息丢失，主要是RFID丢失

**Comment by stephenwang2017** [comment]
换卡，解决
