### ISSUE TITLE
山西石楼阳光宝贝幼儿园，豆豆一班王绍磊，进入宝贝中心会跳到角色绑定页面

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-weiChat#90]
![wechatimg2196](https://user-images.githubusercontent.com/24886936/31485694-42d94350-af67-11e7-959f-859be9a93d91.jpeg)

**Comment by underhill6** [comment]
王绍磊 student_id: 18426
	家长妈妈的电话:18335845349 
	问题原因:
	查询到这个家长在没有绑定前已经添加了同一个电话绑定到这个小朋友的两条数据了,分别是37101和37318。
	但是绑定后只绑定成功了其中一个37318，后面不知道怎么又把这条数据删除了，数据库中还有一条正常的关系数据37101，她又是绑定过了的，再绑定就报“已经与该小朋友绑定，不能重复绑定”的问题了。不能进行绑定了。
	处理措施:
	给她恢复成之前删除的数据37318了，另一条37101做了表中数据的标记删除，她现在已经可以正常进入宝贝中心了。
